# Exercício 1: Carregando e analisando um DataSet

## Dados Estação Cuiabá 2003

In [108]:
import pandas as pd

# Carrega o arquivo csv

dataframe2003 = pd.read_csv('./datasets/INMET_CO_MT_A901_CUIABA_01-01-2003_A_31-12-2003.CSV', delimiter=';', encoding='ISO-8859-1', decimal=',')

print(dataframe2003.isnull().sum().sort_values(ascending=False))
# Exibe os primeiros registros do dataframe
dataframe2003.head()

DATA                                                     0
TEMPERATURA MÖNIMA NA HORA ANT. (AUT) (øC)               0
VENTO, RAJADA MAXIMA (m/s)                               0
VENTO, DIREÇO HORARIA (gr) (ø (gr))                     0
UMIDADE RELATIVA DO AR, HORARIA (%)                      0
UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)                 0
UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)                 0
TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (øC)         0
TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (øC)         0
TEMPERATURA MµXIMA NA HORA ANT. (AUT) (øC)               0
HORA (UTC)                                               0
TEMPERATURA DO PONTO DE ORVALHO (øC)                     0
TEMPERATURA DO AR - BULBO SECO, HORARIA (øC)             0
RADIACAO GLOBAL (KJ/mý)                                  0
PRESSÇO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB)         0
PRESSÇO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB)          0
PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)    0
PRECIPITAÇÃO TOTAL, HORÁRIO (MM)                         0
VENTO, VELOCIDADE HORARIA (m/s)                          0
dtype: int64

,DATA,HORA (UTC),"PRECIPITAÇÃO TOTAL, HORÁRIO (MM)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÇO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÇO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (KJ/mý),"TEMPERATURA DO AR - BULBO SECO, HORARIA (øC)",TEMPERATURA DO PONTO DE ORVALHO (øC),TEMPERATURA MµXIMA NA HORA ANT. (AUT) (øC),TEMPERATURA MÖNIMA NA HORA ANT. (AUT) (øC),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (øC),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (øC),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇO HORARIA (gr) (ø (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)"
0,01/01/2003,00:00,-9999.0,-9999.0,-9999.0,-9999.0,-9999,24.3,23.3,24.7,24.3,23.4,-9999.0,94,92,94,-9999,-9999.0,-9999.0
1,01/01/2003,01:00,-9999.0,-9999.0,-9999.0,-9999.0,-9999,24.7,23.3,24.7,24.3,23.4,-9999.0,94,92,92,-9999,-9999.0,-9999.0
2,01/01/2003,02:00,-9999.0,-9999.0,-9999.0,-9999.0,-9999,24.4,23.2,24.7,24.4,23.4,-9999.0,93,91,93,-9999,-9999.0,-9999.0
3,01/01/2003,03:00,-9999.0,-9999.0,-9999.0,-9999.0,-9999,24.1,23.2,24.9,24.1,23.5,-9999.0,95,92,95,-9999,-9999.0,-9999.0
4,01/01/2003,04:00,-9999.0,-9999.0,-9999.0,-9999.0,-9999,24.5,23.4,24.6,24.1,23.5,-9999.0,95,93,94,-9999,-9999.0,-9999.0

## Dados Estação Cuiabá 2013

In [111]:
# Carregar o arquivo csv

dataframe2013 = pd.read_csv('./datasets/INMET_CO_MT_A901_CUIABA_01-01-2013_A_31-12-2013.CSV', delimiter=';', encoding='ISO-8859-1', decimal=',')
print(dataframe2013.isnull().sum().sort_values(ascending=False))

# Exibe os primeiros registros do dataframe
dataframe2013.head()

DATA                                                     0
TEMPERATURA MÖNIMA NA HORA ANT. (AUT) (øC)               0
VENTO, RAJADA MAXIMA (m/s)                               0
VENTO, DIREÇO HORARIA (gr) (ø (gr))                     0
UMIDADE RELATIVA DO AR, HORARIA (%)                      0
UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)                 0
UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)                 0
TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (øC)         0
TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (øC)         0
TEMPERATURA MµXIMA NA HORA ANT. (AUT) (øC)               0
HORA (UTC)                                               0
TEMPERATURA DO PONTO DE ORVALHO (øC)                     0
TEMPERATURA DO AR - BULBO SECO, HORARIA (øC)             0
RADIACAO GLOBAL (KJ/mý)                                  0
PRESSÇO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB)         0
PRESSÇO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB)          0
PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)    0
PRECIPITAÇÃO TOTAL, HORÁRIO (mm)                         0
VENTO, VELOCIDADE HORARIA (m/s)                          0
dtype: int64

,DATA,HORA (UTC),"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÇO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÇO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (KJ/mý),"TEMPERATURA DO AR - BULBO SECO, HORARIA (øC)",TEMPERATURA DO PONTO DE ORVALHO (øC),TEMPERATURA MµXIMA NA HORA ANT. (AUT) (øC),TEMPERATURA MÖNIMA NA HORA ANT. (AUT) (øC),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (øC),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (øC),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇO HORARIA (gr) (ø (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)"
0,01/01/2013,00:00,0.4,983.5,983.5,982.1,-9999.0,26.1,21.9,28.1,26.1,22.0,20.7,78,64,78,145,4.3,2.1
1,01/01/2013,01:00,1.2,983.9,984.0,983.5,-9999.0,24.7,22.7,26.1,24.5,22.9,22.2,89,78,89,184,4.0,1.4
2,01/01/2013,02:00,0.4,984.4,984.5,983.9,-9999.0,24.5,22.8,24.9,24.5,23.2,22.5,91,88,91,247,3.7,1.6
3,01/01/2013,03:00,0.0,984.9,985.0,984.4,-9999.0,24.4,22.9,24.5,24.2,22.9,22.5,92,90,92,98,3.5,1.9
4,01/01/2013,04:00,0.0,984.3,984.9,984.3,-9999.0,24.4,22.9,24.4,24.2,23.0,22.8,92,91,91,123,3.5,1.2

# Dados Estação Cuiabá 2023

In [122]:
# Carregar o arquivo csv

dataframe2023 = pd.read_csv('./datasets/INMET_CO_MT_A901_CUIABA_01-01-2023_A_31-12-2023.CSV', delimiter=';', encoding='ISO-8859-1', decimal=',')

print(dataframe2023.isnull().sum().sort_values(ascending=False))
#dataframe2023.fillna(value=values, inplace=True)
dataframe2023.replace({'': None}, inplace=True)

print(dataframe2023.isnull().sum().sort_values(ascending=False))
dataframe2023.to_csv('newDataframe2023.csv',na_rep='NaN')
# Exibe os primeiros registros do dataframe
dataframe2023.head()

RADIACAO GLOBAL (Kj/mý)                                  4111
VENTO, RAJADA MAXIMA (m/s)                               3939
VENTO, VELOCIDADE HORARIA (m/s)                          3932
VENTO, DIREÇO HORARIA (gr) (ø (gr))                     3932
PRESSÇO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB)          640
TEMPERATURA MÖNIMA NA HORA ANT. (AUT) (øC)                639
UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)                  639
UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)                  639
TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (øC)          639
TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (øC)          639
TEMPERATURA MµXIMA NA HORA ANT. (AUT) (øC)                639
PRESSÇO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB)           639
PRECIPITAÇÃO TOTAL, HORÁRIO (mm)                          634
TEMPERATURA DO PONTO DE ORVALHO (øC)                      633
TEMPERATURA DO AR - BULBO SECO, HORARIA (øC)              633
UMIDADE RELATIVA DO AR, HORARIA (%)                       633
PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)     633
Hora UTC                                                    0
DATA                                                        0
dtype: int64
RADIACAO GLOBAL (Kj/mý)                                  4111
VENTO, RAJADA MAXIMA (m/s)                               3939
VENTO, VELOCIDADE HORARIA (m/s)                          3932
VENTO, DIREÇO HORARIA (gr) (ø (gr))                     3932
PRESSÇO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB)          640
TEMPERATURA MÖNIMA NA HORA ANT. (AUT) (øC)                639
UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)                  639
UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)                  639
TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (øC)          639
TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (øC)          639
TEMPERATURA MµXIMA NA HORA ANT. (AUT) (øC)                639
PRESSÇO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB)           639
PRECIPITAÇÃO TOTAL, HORÁRIO (mm)                          634
TEMPERATURA DO PONTO DE ORVALHO (øC)                      633
TEMPERATURA DO AR - BULBO SECO, HORARIA (øC)              633
UMIDADE RELATIVA DO AR, HORARIA (%)                       633
PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)     633
Hora UTC                                                    0
DATA                                                        0
dtype: int64

,DATA,Hora UTC,"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÇO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÇO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (Kj/mý),"TEMPERATURA DO AR - BULBO SECO, HORARIA (øC)",TEMPERATURA DO PONTO DE ORVALHO (øC),TEMPERATURA MµXIMA NA HORA ANT. (AUT) (øC),TEMPERATURA MÖNIMA NA HORA ANT. (AUT) (øC),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (øC),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (øC),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇO HORARIA (gr) (ø (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)"
0,01/01/2023,0000 UTC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,01/01/2023,0100 UTC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,01/01/2023,0200 UTC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,01/01/2023,0300 UTC,0.0,990.5,990.5,990.4,NaN,27.5,20.6,27.9,27.5,20.6,20.2,66.0,63.0,66.0,NaN,NaN,NaN
4,01/01/2023,0400 UTC,0.0,990.2,990.5,990.2,NaN,27.3,20.2,27.8,27.3,20.7,20.2,66.0,65.0,65.0,NaN,NaN,NaN

# Exercício 2: Juntando os datasets
### 1.0

In [124]:
import csv
import pandas as pd

# Suponha que você tenha três DataFrames chamados dataframe2003, dataframe2013 e dataframe2023
# Substitua os nomes dos DataFrames pelos seus nomes reais


#Renomeando coluna do datasets
dataframe2023.rename(columns={'Hora UTC':'HORA (UTC)', 'RADIACAO GLOBAL (Kj/mý)': 'RADIACAO GLOBAL (KJ/mý)'}, inplace=True)
dataframe2003.rename(columns={'PRECIPITAÇÃO TOTAL, HORÁRIO (MM)': 'PRECIPITAÇÃO TOTAL, HORÁRIO (mm)'},inplace=True)
#print(dataframe2023)
#print(dataframe2023.columns.values)

#Convertendo coluna DATA para datetime
#dataframe2003['DATA'] = pd.to_datetime(dataframe2003['DATA'], format='%d/%m/%Y', errors='coerce').dt.strftime('%Y/%m/%d')
#print(dataframe2003)
#dataframe2013['DATA'] = pd.to_datetime(dataframe2013['DATA'], format='%d/%m/%Y', errors='coerce').dt.strftime('%Y/%m/%d')
#dataframe2023['DATA'] = pd.to_datetime(dataframe2023['DATA'], format='%d/%m/%Y', errors='coerce').dt.strftime('%Y/%m/%d')

dataframe2003['DATA'] = pd.to_datetime(dataframe2003['DATA'], format='mixed')
#print(dataframe2003)
#dataframe2003.drop('DATA', axis=1, inplace=True)

dataframe2013['DATA'] = pd.to_datetime(dataframe2013['DATA'],format='mixed')
#print(dataframe2013)
#dataframe2013.drop('DATA', axis=1, inplace=True)

dataframe2023['DATA'] = pd.to_datetime(dataframe2023['DATA'],format='mixed')

#print(dataframe2023)
#dataframe2023.drop('DATA', axis=1, inplace=True)
#dataframe2023['HORA (UTC)'] = dataframe2023['HORA (UTC)'].fillna('0000 UTC')

#dataframe2023['HORA (UTC)'] = pd.to_datetime(dataframe2023['HORA (UTC)'],format='ISO8601')
dataframe2023['HORA (UTC)'] = pd.to_datetime(dataframe2023['HORA (UTC)'], format='%H%M UTC', errors='coerce')
dataframe2023['HORA (UTC)'] = dataframe2023['HORA (UTC)'].dt.strftime('%H:%M')
#print(dataframe2023['HORA (UTC)'].value_counts())

#dataframe2023.columns.tolist()
#print(type(df_concat.columns))
#print((dataframe2023.columns))
#print(dataframe2023.info())
#print(dataframe2023['HORA (UTC)'])
#dataframe2023['HORA (UTC)'] = pd.to_datetime(dataframe2023['HORA (UTC)'],format='mixed', utc=True)#.strftime('%H:%M'))
#dataframe2023['HORA (UTC)'] = dataframe2023['HORA (UTC)'].date.dt.strftime('%H:%M')

# Leia os arquivos CSV ou substitua pelo método adequado para carregar seus DataFrames
#dataframe2003 = pd.read_csv('./datasets/INMET_CO_MT_A901_CUIABA_01-01-2003_A_31-12-2003.CSV', sep=';', encoding='ISO-8859-1')
#dataframe2013 = pd.read_csv('./datasets/INMET_CO_MT_A901_CUIABA_01-01-2013_A_31-12-2013.CSV', sep=';', encoding='ISO-8859-1')
#dataframe2023 = pd.read_csv('./datasets/INMET_CO_MT_A901_CUIABA_01-01-2023_A_31-12-2023.CSV', sep=';', encoding='ISO-8859-1')
#print(dataframe2023)

# Concatene os DataFrames ao longo do eixo das linhas
df_concat = pd.concat([dataframe2003, dataframe2013, dataframe2023])
#print(df_concat)

df_concat['DATA'] = pd.to_datetime(df_concat['DATA'])
df_concat['Ano'] = df_concat['DATA'].dt.year
df_concat['Mes'] = df_concat['DATA'].dt.month
df_concat['Dia'] = df_concat['DATA'].dt.day

multiIndex = pd.MultiIndex.from_frame(df_concat[['Ano', 'Mes', 'Dia']])#transforma essas colunas em multi index

df_concat.set_index(multiIndex, inplace=True)
#df_concat.drop('DATA', axis=1, inplace=True)

df_concat.drop(['Ano','Mes','Dia'], axis=1, inplace=True) # substitui a instrução abaixo (iloc)
#df_concat.drop('Mês', axis=1, inplace=True) # mesmo de cima
#df_concat.drop('Dia', axis=1, inplace=True) # mesmo de cima

#df_concat = df_concat.iloc[:, :-3] # slice do dataframe sem 3 ultimas colunas (ano, mes e dia)

#df_concat.to_csv('saida3.csv', index=False)
# Visualize o DataFrame com MultiIndex no índice
#print(df_concat)

#df_concat.columns.tolist()
#print(type(df_concat.columns))


arrayCols=[]
for cols in df_concat.columns:
    tupla=(cols,"")
    if(cols.find("PRESS")!=-1):
        tupla=("PRESSAO",cols)
    elif(cols.find("TEMPERATURA")!=-1):
        tupla=("TEMPERATURA",cols)
    elif(cols.find("UMIDADE")!=-1):
        tupla=("UMIDADE",cols)
    elif(cols.find("VENTO")!=-1):
        tupla=("VENTO",cols)
    arrayCols.append(tupla)

#arrayCols

df_concat.columns = pd.MultiIndex.from_tuples(arrayCols)

#for cols in df_concat.columns:
    #df_concat[cols] = df_concat[cols].replace('-9999.0', pd.nan)
df_concat.replace({-9999.0: None}, inplace=True)

#print(df_concat)
df_concat.to_csv('saida3.csv', index=False,na_rep='NaN')
#print(dataframe2023.head())
print((df_concat.columns.tolist()))

[('DATA', ''), ('HORA (UTC)', ''), ('PRECIPITAÇÃO TOTAL, HORÁRIO (mm)', ''), ('PRESSAO', 'PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)'), ('PRESSAO', 'PRESSÇO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB)'), ('PRESSAO', 'PRESSÇO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB)'), ('RADIACAO GLOBAL (KJ/mý)', ''), ('TEMPERATURA', 'TEMPERATURA DO AR - BULBO SECO, HORARIA (øC)'), ('TEMPERATURA', 'TEMPERATURA DO PONTO DE ORVALHO (øC)'), ('TEMPERATURA', 'TEMPERATURA MµXIMA NA HORA ANT. (AUT) (øC)'), ('TEMPERATURA', 'TEMPERATURA MÖNIMA NA HORA ANT. (AUT) (øC)'), ('TEMPERATURA', 'TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (øC)'), ('TEMPERATURA', 'TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (øC)'), ('UMIDADE', 'UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)'), ('UMIDADE', 'UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)'), ('UMIDADE', 'UMIDADE RELATIVA DO AR, HORARIA (%)'), ('VENTO', 'VENTO, DIRE\x80ÇO HORARIA (gr) (ø (gr))'), ('VENTO', 'VENTO, RAJADA MAXIMA (m/s)'), ('VENTO', 'VENTO, VELOCIDADE HORARIA (m/s)')]

# Exercício 2: Juntando os datasets
### 2.0

In [5]:
'''import pandas as pd

# Suponha que df_concat seja o DataFrame resultante do código anterior

# Cria uma cópia explícita do DataFrame
df_reorganizado = df_concat

# Reordenar as colunas para ter os parâmetros agrupados
ordem_colunas = ['PRECIPITAÇÃO TOTAL, HORÁRIO (mm)', 
                 'PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)',
                 'RADIACAO GLOBAL (KJ/m²)',
                 'TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)',
                 'UMIDADE RELATIVA DO AR, HORARIA (%)',
                 'VENTO, VELOCIDADE HORARIA (m/s)']

# Selecionar apenas as colunas que estão presentes no DataFrame
#colunas_presentes = [coluna for coluna in ordem_colunas if coluna in df_reorganizado.columns.get_level_values(1)]
#df_reorganizado = df_reorganizado.loc[:, colunas_presentes]

# Adicionar MultiIndex nas colunas
#df_reorganizado.columns = pd.MultiIndex.from_product([['Mes', 'Dia'], df_reorganizado.columns.get_level_values(1)])

# Visualizar o DataFrame reorganizado com MultiIndex nas colunas
#print(df_reorganizado)
#----------------

#print(ordem_colunas)


#print(df_reorganizado.columns.get_level_values(0))

for tmp in ordem_colunas:
    print(tmp)
    #print(tmp.get_level_values(1))
#colunas_presentes1 = [coluna for coluna in ordem_colunas]
#print(colunas_presentes1)

'''

"import pandas as pd\n\n# Suponha que df_concat seja o DataFrame resultante do código anterior\n\n# Cria uma cópia explícita do DataFrame\ndf_reorganizado = df_concat\n\n# Reordenar as colunas para ter os parâmetros agrupados\nordem_colunas = ['PRECIPITAÇÃO TOTAL, HORÁRIO (mm)', \n                 'PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)',\n                 'RADIACAO GLOBAL (KJ/m²)',\n                 'TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)',\n                 'UMIDADE RELATIVA DO AR, HORARIA (%)',\n                 'VENTO, VELOCIDADE HORARIA (m/s)']\n\n# Selecionar apenas as colunas que estão presentes no DataFrame\n#colunas_presentes = [coluna for coluna in ordem_colunas if coluna in df_reorganizado.columns.get_level_values(1)]\n#df_reorganizado = df_reorganizado.loc[:, colunas_presentes]\n\n# Adicionar MultiIndex nas colunas\n#df_reorganizado.columns = pd.MultiIndex.from_product([['Mes', 'Dia'], df_reorganizado.columns.get_level_values(1)])\n\n# Visualizar o DataFrame reorganizado com MultiIndex nas colunas\n#print(df_reorganizado)\n#----------------\n\n#print(ordem_colunas)\n\n\n#print(df_reorganizado.columns.get_level_values(0))\n\nfor tmp in ordem_colunas:\n    print(tmp)\n    #print(tmp.get_level_values(1))\n#colunas_presentes1 = [coluna for coluna in ordem_colunas]\n#print(colunas_presentes1)\n\n"

__Exercício 3: Analisando os DataFrame__

*  Com base nos três ``DataFrame`` carregados:
1. Analisando as colunas relacionadas e precipitações e temperaturas, compare as médias, os valores mínimos e máximos em cada um dos anos. 
2. Compare os mesmos dados do exercício anterior mas para o mes de Janeiro de cada um dos três anos. 
3. Considere uma aproximação para as estações do ano no brasil dada por: Verão (Janeiro, Fevereiro e Março), Outono (Abril, Maio e Junho), Inverno (Julho, Agosto e Setembro) Primavera (Outubro, Novembro e Dezembro). Compare as informações sobre temperatura e precipitações medias em cada uma das estações dos três anos. 
4. Repare que os dados de cada estação são monitorando de hora em hora. Considere os intervalos de um dia como sendo: Madrugada (00:00 a 06:00), Manha (06:00 a 12:00), Tarde (12:00 a 18:00) e Noite (18:00 a 00:00). Compare as informações sobre temperatura e precipitações medias para o dia 28 de setembro  em cada um dos intervalos do dia dos três anos.

__Exercício 3: Analisando os DataFrame__

*  Com base nos três ``DataFrame`` carregados:
1. Analisando as colunas relacionadas de precipitações e temperaturas, compare as médias, os valores mínimos e máximos em cada um dos anos.

In [126]:
#df_concat['TEMPERATURA'].astype('float')
print(df_concat.groupby('Ano')['PRECIPITAÇÃO TOTAL, HORÁRIO (mm)'].agg(['min','max','mean']))
#print(df_concat.groupby('Ano')['PRECIPITAÇÃO TOTAL, HORÁRIO (mm)'].agg(['max']))
#print(df_concat.groupby('Ano')['PRECIPITAÇÃO TOTAL, HORÁRIO (mm)'].agg(['mean']))
print(df_concat.groupby('Ano')['TEMPERATURA'].agg(['min','max','mean']))
#print(df_concat.groupby('Ano')['TEMPERATURA'].agg(['max']))
#print(df_concat.groupby('Ano')['TEMPERATURA'].agg(['mean']))

#df_concat.head()
#df_concat.info()

      min   max      mean
Ano
2003  0.0  31.0  0.105662
2013  0.0  59.0  0.144678
2023  0.0  41.2  0.124637
                                      TEMPERATURA                   \
     TEMPERATURA DO AR - BULBO SECO, HORARIA (øC)
                                              min   max       mean
Ano
2003                                         12.2  38.9  26.072362
2013                                          8.9  39.2  26.319622
2023                                         10.0  43.2  28.599459

                                                            \
     TEMPERATURA DO PONTO DE ORVALHO (øC)
                                      min   max       mean
Ano
2003                                  2.9  24.9  19.299684
2013                                 -4.3  25.2  18.643467
2023                                  3.8  24.3  17.604061

                                                                  \
     TEMPERATURA MµXIMA NA HORA ANT. (AUT) (øC)
                                            min   max       mean
Ano
2003                                       13.5  39.2  26.722075
2013                                        9.1  39.8  26.924634
2023                                       10.2  43.3  29.279461

                                                                  \
     TEMPERATURA MÖNIMA NA HORA ANT. (AUT) (øC)
                                            min   max       mean
Ano
2003                                       11.7  38.0    25.4371
2013                                        8.8  37.7  25.748959
2023                                        9.9  42.0  27.935143

                                                                        \
     TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (øC)
                                                  min   max       mean
Ano
2003                                              3.8  25.7  19.833669
2013                                             -3.2  25.8  19.134039
2023                                              5.0  24.9  18.147457


     TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (øC)
                                                  min   max       mean
Ano
2003                                              2.4  24.2  18.638451
2013                                             -6.4  24.0  18.166259
2023                                              2.9  23.5  17.089496

-------------------------------------------------------------------------------------
2. Compare os mesmos dados do exercício anterior mas para o mes de Janeiro de cada um dos três anos.

In [131]:
# Dados selecionados pelo mes de janeiro
df_meses1 = df_concat[df_concat['DATA'].dt.month.isin([1])]
#print(df_meses1)
df_meses1.to_csv('meses1_out.csv', index=False,na_rep='NaN')

# Agrupamento por anos, para obter
result = df_meses1.groupby('Ano')['PRECIPITAÇÃO TOTAL, HORÁRIO (mm)'].agg(['min', 'max', 'mean'])

# Print result
print(result)

print('Precipitação total: Valores correspondentes ao mes de Janeiro')
if(df_concat['DATA'].dt.month.any() == 1):
    print(df_concat.groupby('Ano')['PRECIPITAÇÃO TOTAL, HORÁRIO (mm)'].agg(['min', 'max', 'mean']))
    #print(df_concat.groupby('Ano')['PRECIPITAÇÃO TOTAL, HORÁRIO (mm)'].agg(['max']))
    #print(df_concat.groupby('Ano')['PRECIPITAÇÃO TOTAL, HORÁRIO (mm)'].agg(['mean']))

print()
print('Temperatura: Valores correspondentes ao mes de Janeiro')
if(df_concat['DATA'].dt.month.any() == 1):
    print(df_concat.groupby('Ano')['TEMPERATURA'].agg(['min', 'max', 'mean']))
    #print(df_concat.groupby('Ano')['TEMPERATURA'].agg(['max']))
    #print(df_concat.groupby('Ano')['TEMPERATURA'].agg(['mean']))

      min   max      mean
Ano
2003  0.0  14.2  0.262025
2013  0.0  18.0  0.244355
2023  0.0  41.2  0.265465
Precipitação total: Valores correspondentes ao mes de Janeiro
      min   max      mean
Ano
2003  0.0  31.0  0.105662
2013  0.0  59.0  0.144678
2023  0.0  41.2  0.124637

Temperatura: Valores correspondentes ao mes de Janeiro
                                      TEMPERATURA                   \
     TEMPERATURA DO AR - BULBO SECO, HORARIA (øC)
                                              min   max       mean
Ano
2003                                         12.2  38.9  26.072362
2013                                          8.9  39.2  26.319622
2023                                         10.0  43.2  28.599459

                                                            \
     TEMPERATURA DO PONTO DE ORVALHO (øC)
                                      min   max       mean
Ano
2003                                  2.9  24.9  19.299684
2013                                 -4.3  25.2  18.643467
2023                                  3.8  24.3  17.604061

                                                                  \
     TEMPERATURA MµXIMA NA HORA ANT. (AUT) (øC)
                                            min   max       mean
Ano
2003                                       13.5  39.2  26.722075
2013                                        9.1  39.8  26.924634
2023                                       10.2  43.3  29.279461

                                                                  \
     TEMPERATURA MÖNIMA NA HORA ANT. (AUT) (øC)
                                            min   max       mean
Ano
2003                                       11.7  38.0    25.4371
2013                                        8.8  37.7  25.748959
2023                                        9.9  42.0  27.935143

                                                                        \
     TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (øC)
                                                  min   max       mean
Ano
2003                                              3.8  25.7  19.833669
2013                                             -3.2  25.8  19.134039
2023                                              5.0  24.9  18.147457


     TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (øC)
                                                  min   max       mean
Ano
2003                                              2.4  24.2  18.638451
2013                                             -6.4  24.0  18.166259
2023                                              2.9  23.5  17.089496

3. Considere uma aproximação para as estações do ano no brasil dada por: Verão (Janeiro, Fevereiro e Março), Outono (Abril, Maio e Junho), Inverno (Julho, Agosto e Setembro) Primavera (Outubro, Novembro e Dezembro). Compare as informações sobre temperatura e precipitações medias em cada uma das estações dos três anos.

In [180]:
print('Verão')
# Selecionar dados com base nos meses 1, 2 e 3
df_verao = df_concat[df_concat['DATA'].dt.month.isin([1, 2, 3])]
result = df_verao['PRECIPITAÇÃO TOTAL, HORÁRIO (mm)'].agg(['min', 'max', 'mean'])

#result = df_verao.groupby(['Ano'])['PRECIPITAÇÃO TOTAL, HORÁRIO (mm)'].agg(['min', 'max', 'mean'])
result1 = df_concat[df_concat['DATA'].dt.month.isin([1,2,3])]['PRECIPITAÇÃO TOTAL, HORÁRIO (mm)'].agg(['min', 'max', 'mean'])

result2 = df_concat[df_concat['DATA'].dt.month.between(1, 3)]['PRECIPITAÇÃO TOTAL, HORÁRIO (mm)'].agg(['min', 'max', 'mean'])

# Print result
print('RESULT')
print(result)
print('RESULT1')
print(result1)
print('RESULT2')
print(result2)

print('Outono')
# Selecionar dados com base nos meses 1, 2 e 3
df_outono = df_concat[df_concat['DATA'].dt.month.isin([4, 5, 6])]
result = df_outono['PRECIPITAÇÃO TOTAL, HORÁRIO (mm)'].agg(['min', 'max', 'mean'])
print(result)

print('Inverno')
# Selecionar dados com base nos meses 1, 2 e 3
df_inverno = df_concat[df_concat['DATA'].dt.month.isin([7, 8, 9])]
result = df_inverno['PRECIPITAÇÃO TOTAL, HORÁRIO (mm)'].agg(['min', 'max', 'mean'])
print(result)

print('Primavera')
# Selecionar dados com base nos meses 1, 2 e 3
df_primavera = df_concat[df_concat['DATA'].dt.month.isin([10, 11, 12])]
result = df_primavera['PRECIPITAÇÃO TOTAL, HORÁRIO (mm)'].agg(['min', 'max', 'mean'])
print(result)

print('-'*20)
print('Precipitação total: Valores correspondentes ao mes de Janeiro')
#print(df_concat[df_concat['DATA'].dt.month==2])

#if(
verao=pd.concat([df_concat[df_concat['DATA'].dt.month == 1],
                    df_concat[df_concat['DATA'].dt.month == 2],
                    df_concat[df_concat['DATA'].dt.month == 3]])
    #print('>>',df_concat['DATA'].dt.month)
    #verao=df_concat['PRECIPITAÇÃO TOTAL, HORÁRIO (mm)']
#verao.to_csv("veraoooo.csv")    
#print(verao)
print(verao['PRECIPITAÇÃO TOTAL, HORÁRIO (mm)'].agg(['min','max','mean']))
#print(df_concat['PRECIPITAÇÃO TOTAL, HORÁRIO (mm)'].agg(['max']))
#print(df_concat['PRECIPITAÇÃO TOTAL, HORÁRIO (mm)'].agg(['mean']))

print('='*20)
'''print('Temperatura: Valores correspondentes ao mes de Janeiro')
if(df_concat['DATA'].dt.month.any() == 1):
    print(df_concat.groupby('Ano')['TEMPERATURA'].agg(['min']))
    print(df_concat.groupby('Ano')['TEMPERATURA'].agg(['max']))
    print(df_concat.groupby('Ano')['TEMPERATURA'].agg(['mean']))
'''

Verão
RESULT
min      0.000000
max     59.000000
mean     0.227501
Name: PRECIPITAÇÃO TOTAL, HORÁRIO (mm), dtype: float64
RESULT1
min      0.000000
max     59.000000
mean     0.227501
Name: PRECIPITAÇÃO TOTAL, HORÁRIO (mm), dtype: float64
RESULT2
min      0.000000
max     59.000000
mean     0.227501
Name: PRECIPITAÇÃO TOTAL, HORÁRIO (mm), dtype: float64
Outono
min      0.000000
max     34.000000
mean     0.072444
Name: PRECIPITAÇÃO TOTAL, HORÁRIO (mm), dtype: float64
Inverno
min      0.00000
max     21.40000
mean     0.05232
Name: PRECIPITAÇÃO TOTAL, HORÁRIO (mm), dtype: float64
Primavera
min      0.000000
max     48.400000
mean     0.157575
Name: PRECIPITAÇÃO TOTAL, HORÁRIO (mm), dtype: float64
--------------------
Precipitação total: Valores correspondentes ao mes de Janeiro
min      0.000000
max     59.000000
mean     0.227501
Name: PRECIPITAÇÃO TOTAL, HORÁRIO (mm), dtype: float64
====================

"print('Temperatura: Valores correspondentes ao mes de Janeiro')\nif(df_concat['DATA'].dt.month.any() == 1):\n    print(df_concat.groupby('Ano')['TEMPERATURA'].agg(['min']))\n    print(df_concat.groupby('Ano')['TEMPERATURA'].agg(['max']))\n    print(df_concat.groupby('Ano')['TEMPERATURA'].agg(['mean']))\n"

4. Repare que os dados de cada estação são monitorando de hora em hora. Considere os intervalos de um dia como sendo: Madrugada (00:00 a 06:00), Manha (06:00 a 12:00), Tarde (12:00 a 18:00) e Noite (18:00 a 00:00). Compare as informações sobre temperatura e precipitações medias para o dia 28 de setembro  em cada um dos intervalos do dia dos três anos.